# Generated by Django 4.1.7 on 2023-03-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0003_product_category_product_sub_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
