# Generated by Django 4.1.7 on 2023-03-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0005_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
