# Generated by Django 4.1.7 on 2023-03-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0007_alter_product_category_alter_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jewellery/diamondimg')),
                ('name', models.CharField(max_length=100)),
                ('shape', models.CharField(choices=[('round', ' Round'), ('princess', ' Princess'), ('pear', ' Pear'), ('heart', ' Heart'), ('asscher', ' Asscher'), ('cushion', ' Cushion'), ('oval', ' Oval'), ('radiant', ' Radiant')], default='round', max_length=50)),
                ('carat', models.FloatField()),
                ('color', models.CharField(choices=[('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K')], default='D', max_length=10)),
                ('clarity', models.CharField(choices=[('FL', 'FL'), ('IF', 'IF'), ('VVS1', 'VVS1'), ('VVS2', 'VVS2'), ('VS1', 'VS1'), ('VS2', 'VS2'), ('SI1', 'SI1'), ('SI2', 'SI2')], default='FL', max_length=50)),
                ('cut', models.CharField(choices=[('H&A', 'H&A'), ('Excellent', 'Excellent'), ('V Good', 'V Good')], default='H&A', max_length=50)),
                ('symmetry', models.CharField(choices=[('Excellent', 'Excellent'), ('V Good', 'V Good'), ('Good', 'Good')], default='Excellent', max_length=50)),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
