# Generated by Django 4.1.7 on 2023-03-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0008_diamond'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='jewellery/categoryimg'),
        ),
    ]
