# Generated by Django 4.1.7 on 2023-03-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0009_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
