# Generated by Django 4.1.7 on 2023-03-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0010_product_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_info',
            field=models.TextField(default='NO Additonal Info'),
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default='bhjsha'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(default='ESTSS', max_length=150),
        ),
    ]
