# Generated by Django 4.1.7 on 2023-03-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0013_remove_product_add_info_remove_product_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_info',
            field=models.TextField(default='NO Additonal Info'),
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default='Descrpition here'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(default='Meta_title descrpition here', max_length=150),
        ),
    ]
