# Generated by Django 4.1.7 on 2023-03-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0014_product_add_info_product_desc_product_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Orange', 'Orange'), ('Black', 'Black'), ('Peal', 'Peal')], default='Gold', max_length=10),
        ),
    ]
