# Generated by Django 4.1.7 on 2023-03-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0015_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamond',
            name='add_info',
            field=models.TextField(default='NO Additonal Info'),
        ),
        migrations.AddField(
            model_name='diamond',
            name='desc',
            field=models.TextField(default='Descrpition here'),
        ),
        migrations.AddField(
            model_name='diamond',
            name='meta_title',
            field=models.CharField(default='Meta_title descrpition here', max_length=150),
        ),
    ]
